### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by pravasna** [pravasna/mysecondgitrepo#3]
Use [Ref](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) . Add @pravasna as the codeowner

**Comment by reddymsiva** [comment]
*       @global-pravasana @global-reddymsiva

**Comment by pravasna** [comment]
"* @pravasna" Just add this in the CODEOWNERS file
